---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: infra-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infra-test
  template:
    metadata:
      labels:
        app: infra-test
    spec:
      containers:
        - name: infra-test
          image: nilimapaul002/infra-test:v2
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: infra-test
spec:
  selector:
    app: infra-test
  ports:
    - name: http
      port: 8080
      targetPort: 8080